version: '2.1'
services:
  weatherforecast-web:
    ports:
      - 6001:80
    environment:
      - Console__Enabled=true
  mssql:
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=yourStrong(!)Password
    restart: always
    volumes:
      - sql-weatherforecast:/var/opt/mssql-weatherforecast
      - './db:/home'
    healthcheck:
      test:
        ['CMD', '/opt/mssql-tools/bin/sqlcmd', '-U', 'sa', '-P', 'yourStrong(!)Password', '-Q', 'select 1']
      interval: 5s
      timeout: 5s
      retries: 12
volumes:
  sql-weatherforecast:
